### ISSUE TITLE
Unauthorized resource access

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/dci-ansible#12]
When you try to access to a resource which is not authorized for your team, you get a stack trace because the http return code 412 is not handled correctly.

This is an exemple with dci_topic:
```
        - name: Retrieve information about the next topic
          dci_topic:
            id: '{{ job_informations.job.topic.next_topic }}'
```
If you have access to the current topic but not the next topic :

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_KVNLtV/ansible_module_dci_topic.py", line 187, in <module>
    main()
  File "/tmp/ansible_KVNLtV/ansible_module_dci_topic.py", line 181, in main
    result = parse_http_response(http_response, dci_topic, context, module)
  File "/tmp/ansible_KVNLtV/ansible_modlib.zip/ansible/module_utils/common.py", line 172, in parse_http_response
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decode
```

**Comment by dsavineau** [comment]
This issue will be adresses on the api side : https://softwarefactory-project.io/r/#/c/12198/
