### ISSUE TITLE
The 'cryptography' distribution was not found and is required by ansible

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible#9]
```
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 29, in <module>
    from ansible.inventory.data import InventoryData
  File "/usr/lib/python2.7/site-packages/ansible/inventory/data.py", line 29, in <module>
    from ansible.plugins.cache import FactCache
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 30, in <module>
    from ansible.plugins.loader import cache_loader
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 22, in <module>
    from ansible.parsing.plugin_docs import read_docstring
  File "/usr/lib/python2.7/site-packages/ansible/parsing/plugin_docs.py", line 12, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 58, in <module>
    from Crypto.Cipher import AES as AES_pycrypto
  File "build/bdist.linux-x86_64/egg/Crypto/Cipher/AES.py", line 50, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Cipher/_AES.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/Crypto/Cipher/_AES.py", line 3, in __bootstrap__
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'cryptography' distribution was not found and is required by ansible
```
ansible-2.4.2.0-1.el7.noarch

I had the problem on RHEL7. Looks like a packaging issue to me. I fixed that with: `yum install -y python-cryptography`

**Comment by goneri** [comment]
Fixed.
